### ISSUE TITLE
Implement existing use of action-API

### ISSUE THREAD

**Issue by dolhuis** [Amsterdam/dcatd#2]
Amsterdam CityData frontend uses a subset of the current [CKAN action API](http://docs.ckan.org/en/latest/api/index.html). First of all let the API of this microservice mimic the current, limited, use of the CKAN API.

**Comment by jsoetendal** [comment]
See: https://dokuwiki.datapunt.amsterdam.nl/doku.php?id=start:datapunt:catalogus:functioneelontwerp#huidig_gebruik_ckan_api for specification how API is currently used in front-end.

**Comment by dolhuis** [comment]
=== Current use API ===
  * catalogus/api/3/action/package_search (http://docs.ckan.org/en/latest/api/index.html?highlight=package_search#ckan.logic.action.get.package_search)
    * Parameters:
      * `start`: for pagination
      * `rows`:  for pagination
      * `facet.field`:
        * facets 'groups' (Thema), 'res_format' (Formaat) en 'organizations' (Gepubliceerd door)
      * `fq`, filtering on facets (facet query):
        * 'groups', (= Thema)
        * 'res_format' (= Formaat) and
        * 'organization' (= Gepubliceerd door)
      * `sort`: ordering (only 'name asc' is used)
      * `q`: free search
    * Example requests of our current implementation:
      * City data starting page: https://api.data.amsterdam.nl/catalogus/api/3/action/package_search?facet.field=%5B%22groups%22,%22res_format%22,%22organization%22%5D&fq=&rows=100&sort=name+asc&start=0
      * Filtering down on facets: https://api.data.amsterdam.nl/catalogus/api/3/action/package_search?facet.field=%5B%22groups%22,%22res_format%22,%22organization%22%5D&fq=groups:%22energie%22+res_format:%22CSV%22+organization:%22gemeente-amsterdam-ruimte-en-duurzaamheid%22&q=Potentie&rows=100&sort=name+asc&start=0
    * See the sources where this is being used (GitHub):
      * https://github.com/DatapuntAmsterdam/atlas/blob/develop/modules/data-selection/services/api/data-selection-api-ckan.factory.js#L8
      * https://github.com/DatapuntAmsterdam/atlas/blob/develop/modules/data-selection/data-selection-config.constant.js#L128
    * Request used by our TypeAhead service:
      * https://api.data.amsterdam.nl/catalogus/api/3/action/package_search
    * See the sources where this is being used in TypeAhead (Github)
      * https://github.com/Amsterdam/typeahead/blob/master/typeahead/conf.py#l84
  * catalogus/api/3/action/package_show (http://docs.ckan.org/en/latest/api/index.html?highlight=package_show#ckan.logic.action.get.package_show)
    * Parameters:
      * `id` (To get the details of a complete dataset)
    * Example requests in Amsterdam City Data:
      * https://api.data.amsterdam.nl/catalogus/api/3/action/package_show?id=c5429174-b7c0-49b7-be78-030cecec4b02
    * See the sources where this is being used in Amsterdam City Data (GitHub)
      * https://github.com/DatapuntAmsterdam/atlas/blob/develop/modules/data-selection/data-selection-config.constant.js#L132
  * catalogus/api/3/action/package_list (http://docs.ckan.org/en/latest/api/index.html?highlight=package_list#ckan.logic.action.get.package_list)
    * Parameters:
      * none
    * Example request:
      * https://api.data.amsterdam.nl/catalogus/api/3/action/package_list
    * Current use:
      * data.overheid.nl uses `package_list` and subsequent `package_show` to sync the datasets in our catalog to their own.

**Comment by dolhuis** [comment]
## Additional remarks

### Usage:
Both [Amsterdam City Data](https://data.amsterdam.nl/) and [data.overheid.nl](https://data.overheid.nl) use our API.

### package_show endpoint:
The package_show endpoint consumes the `id` paramater, but returns both matches on 'id' and 'name' (and data.overheid.nl uses the name to query us, so this should also be honoured in the minimal implementation).

**Comment by dolhuis** [comment]
This is no longer required. It has been resolved in a different way.
